# GIẢI HỆ PHƯƠNG TRÌNH TUYẾN TÍNH BẰNG PHƯƠNG PHÁP GAUSS-JORDAN

## I. Mã giả

Một hệ phương trình tuyến tính gồm n phương trình, n ẩn có dạng:

$
\begin{cases}
a_{11}x_{1} + a_{12}x_{2} + \dots + a_{1n}x_{n} = b_{1} \\
a_{21}x_{1} + a_{22}x_{2} + \dots + a_{2n}x_{n} = b_{2} \\
\vdots \\
a_{n1}x_{1} + a_{n2}x_{2} + \dots + a_{nn}x_{n} = b_{n}
\end{cases}
$

Đặt A là ma trận các hệ số, X là cột các ẩn, B là cột các hệ số tự do, khi đó hệ phương trình trên được viết dưới dạng AX = B
Khi đó $\~{A} = (A | B)$ là ma trận mở rộng của hệ phương trình trên

Phần này trình bày cách giải hệ phương trình tuyến tính bằng phương pháp Gauss-Jordan:

***Bước 1:*** Lập ma trận mở rộng $\~{A} = (A|B)$

***Bước 2:*** Đưa ma trận $\~{A}$ về dạng bậc thang rút gọn bằng thuật toán Gauss-Jordan

***Bước 3:*** Dựa vào trường hợp của dạng bậc thang rút gọn $R_{A}$ mà kết luận nghiệm cụ thể


### 1. Thuật toán Gauss-Jordan
#### Tìm dạng bậc thang rút gọn của ma trận $A \in M_{m \times n} (\mathbb{R})$

***Bước 1:*** Cho i := 0, j := 0

***Bước 2:*** Nếu i >= m hoặc j >= n thì kết thúc 

***Bước 3:*** 
- Nếu $a_{i, j}$ $\neq$ 0, thực hiện các phép biến đổi: 

    - $\frac{1}{a_{i, j}} d_{i}$

    - $d_{k} - a_{k, j}d_{i}$ với mọi k $\neq i$

    Sau đó i := i + 1, j := j + 1 và quay về Bước 2

- Nếu $a_{i, j} = 0$, chuyển sang Bước 4:

    - Nếu $a_{k, j} \neq 0$ với một k > i nào đó thì chọn một k như vậy và thực hiện phép biến đổi dòng $d_{i} \leftrightarrow d_{k}$ và quay về Bước 2
    - Nếu $a_{k, j} = 0$ với mọi k > i thì j := j + 1 và quay về Bước 2 


### 2. Giải hệ phương trình
#### Dựa vào các trường hợp của dạng bậc thang rút gọn của $\~{A}$ để kết luận nghiệm

Ta tính hạng r(A) của ma trận A và hạng r($\~{A}$) của ma trận mở rộng $\~{A}$

***Trường hợp 1:*** r(A) < r($\~{A}$). Kết luận hệ phương trình vô nghiệm

***Trường hợp 2:*** r(A) = r($\~{A}$) = n, tức là ma trận mở rộng có dạng

$
\begin{bmatrix}
1 & 0 & 0 \dots 0 & | & a_{1} \\
0 & 1 & 0 \dots 0 & | & a_{2} \\
\dots & \dots & \dots & & \dots \\
0 & 0 & 0 \dots 1 & | & a_{n} \\
\end{bmatrix}
$

Khi đó hệ phương trình có nghiệm duy nhất là:
    $x_{1} = a_{1}, x_{2} = a_{2}, \dots , x_{n} = a_{n}$

***Trường hợp 3:*** khác 2 trường hợp trên, khi đó hệ có vô số nghiệm sao cho:
- Ẩn tương ứng với các cột không có phần tử cơ sở 1 sẽ là ẩn tự do (lấy giá trị tùy ý)

- Ẩn tương ứng với cột có phần tử cơ sở 1 sẽ được tính theo các ẩn tự do

## II. Cài đặt chương trình

### 1. Khai báo thư viện

In [100]:
import numpy as np

### 2. Hàm phụ trợ

In [101]:
def swap_i_rows(mat, row1, row2):               # Hoan vi 2 dong
    tmp = mat[row1].copy()
    mat[row1] = mat[row2]
    mat[row2] = tmp
    return

def find_mat_rank(aug_mat, n):                  # Tim hang cua ma tran bac thang
    cnt = 0
    for i in range(n):
        for j in range(n):
            if aug_mat[i][j] != 0:
                cnt += 1
                break
    return cnt

def find_aug_mat_rank(aug_mat, n):              # Tim hang cua ma tran bac thang mo rong
    cnt = 0
    for i in range(n):
        for j in range(n + 1):
            if aug_mat[i][j] != 0:
                cnt += 1
                break
    return cnt

### 3. Nhập ma trận mở rộng

In [102]:
n = int(input("Nhap n = "))
aug_mat = np.ones((n, n + 1), dtype = 'float64')

for i in range(n):
    row_input = input(f"Nhap dong {i} cua ma tran A: ").split(sep = ' ')
    for j in range(n):
        aug_mat[i][j] = row_input[j]
        
row_input = input("Nhap ma tran B: ").split(sep = ' ')
for i in range(n):
    aug_mat[i][n] = row_input[i]
        
aug_mat = aug_mat.astype(float)

print("Ma tran mo rong (A|B): ")
print(aug_mat)

Ma tran mo rong (A|B): 
[[1. 7. 0. 0. 8. 5.]
 [0. 0. 1. 2. 6. 3.]
 [0. 0. 0. 1. 9. 5.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### 4. Đưa ma trận mở rộng về dạng bậc thang rút gọn

In [103]:
def to_Gauss_Jordan_form(aug_mat ,n):        
    i_row = 0
    i_col = 0

    while i_row < n and i_col < n:
        if aug_mat[i_row][i_col] != 0:
            aug_mat[i_row] *= (1.0 / aug_mat[i_row][i_col])
            for j in range(n):
                if j != i_row:
                    aug_mat[j] -= (aug_mat[j][i_col] * aug_mat[i_row])
            i_row += 1
            i_col += 1
            continue
        else:
            for j in range(i_row + 1, n):
                if aug_mat[j][i_col] != 0:
                    swap_i_rows(aug_mat, i_row, j)
                    break
            else:
                i_col += 1
                
to_Gauss_Jordan_form(aug_mat, n)
print(aug_mat)

[[  1.   7.   0.   0.   8.   5.]
 [  0.   0.   1.   0. -12.  -7.]
 [  0.   0.   0.   1.   9.   5.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


### 5. Giải hệ phương trình dựa trên ma trận bậc thang rút gọn

In [104]:
def solve_equation_system(aug_mat, n):
    mat_rank = find_mat_rank(aug_mat, n)
    aug_mat_rank = find_aug_mat_rank(aug_mat, n)
    
    # Trường hợp 1
    if mat_rank < aug_mat_rank:
        print("He phuong trinh vo nghiem. ")
        return
    
    # Trường hợp 2
    elif mat_rank == aug_mat_rank and mat_rank == n:
        print("He phuong trinh co 1 nghiem duy nhat: ")
        for i in range(n):
            print(f"x{i + 1} = {aug_mat[i][n]}")
        return
    
    # Trường hợp 3
    else:
        print("He phuong trinh co vo so nghiem: ")
        i_row = 0
        i_col = 0
        while i_row < n and i_col < n:
            if aug_mat[i_row][i_col] == 1:
                print(f"x{i_col + 1} = {aug_mat[i_row][n]}", end = '')
                for j in range(i_col + 1, n):
                    if aug_mat[i_row][j] != 0:
                        print(f" + ({-aug_mat[i_row][j]} * x{j + 1})", end = '')
                print("")
                i_row += 1
                i_col += 1
            else:
                print(f"x{i_col + 1} ∈ R")
                i_col += 1
             
solve_equation_system(aug_mat, n)

He phuong trinh co vo so nghiem: 
x1 = 5.0 + (-7.0 * x2) + (-8.0 * x5)
x2 ∈ R
x3 = -7.0 + (12.0 * x5)
x4 = 5.0 + (-9.0 * x5)
x5 ∈ R


## III. Phân tích độ phức tạp thuật toán

Xét ma trận A $\in$ $M_{m \times n}$ có bậc r.

Với mỗi r $\in$ [0, min(m, n)]:
Ta xét biến i chạy từ 1 đến r, với mỗi i:
- Thực hiện rút gọn dòng i sao cho phần tử cơ sở = 1 $\rightarrow$ n + 1 - i thao tác
- Với mọi j $\neq$ i rút gọn dòng j sao cho chỉ có duy nhất phần tử cơ sở = 1 trên một cột $\rightarrow$ (m - 1)$\times$(n + 1 - i) thao tác

Từ đó ta có hàm độ phức tạp phụ thuộc theo 3 biến r, m, n là f(r, m, n):

$$
\begin{split}
f(r, m, n) &= n + (m - 1)n + (n - 1) + (m - 1)(n - 1) + ... + (n - r + 1) + (m - 1)(n - r + 1)\\
&= \frac{(2n - r + 1)r}{2} + (m-1)\frac{(2n - r + 1)r}{2}\\
&= m\frac{(2n - r + 1)r}{2}
\end{split}
$$

Xét ma trận vuông A $\in$ $M_{n \times n}$ tại trường hợp xấu nhất r = n, khi đó ta có hàm độ phức tạp f(n):

$$
f(n) = \frac{n(n + 1)n}{2} = \frac{n^3}{2} + \frac{n^2}{2}
$$

Vậy độ phức tạp cho trường hợp xấu nhất là: O($\frac{n^3}{2}$)


